article: https://www.hackster.io/157756/hardwario-iot-kit-smart-alarm-system-493d48
articles:
  - title: HARDWARIO IoT Kit Light Control of LED Strip
    url: https://www.hackster.io/jakub-smejkal/bigclown-smart-alarm-system-493d48
    description: Make an affordable but smart Alarm system for your home, or any of your buildings. It can run up to 2 years just from batteries.
    images:
      - url: https://hackster.imgix.net/uploads/attachments/1050367/_cNdHJ2vbPU.blob?auto=compress%2Cformat&w=900&h=675&fit=min
images:
  - title:
    url: https://github.com/hardwario/website/blob/master/static/kits-images/motion-detector/main.png
assembly:
  - name: HARDWARIO PIR Module
  - name: HARDWARIO Core Module
  - name: HARDWARIO Mini Battery Module
